stages:
- build

artifacts:
  image: tianon/latex
  stage: build
  before_script:
  - apt-get install enscript
  script:
  - cd paper && ./build.sh
  - cd ../presentation && ./build.sh
  - cd ../revisions && ./build.sh
  - cd ..
  artifacts:
    paths:
    - paper/dist/paper.pdf
    - revisions/dist/revision.pdf
    - presentation/dist/presentation.pdf
    - ipe-submission/paper.docx
